### PR TITLE
Fix build of whitelabel demo Sass

### PR DESCRIPTION
**Pull request by notlee**
fixes: https://github.com/Financial-Times/o-message/issues/91

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-message bundle size difference from 4.1.6 to 4ea13c36d3f1550a0918d92142cba62a4406aee4
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
👋 Percy has finished running the visual regression testing!

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v4.1.7 :tada:

**Comment by notlee** [comment]
thanks @JakeChampion. Likely this will crop up again unless we verify demo builds work for each brand in the future: https://github.com/Financial-Times/origami-build-tools/issues/884

**Pull request merged**
